version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: quiz_competition
      POSTGRES_PASSWORD: "aY5kGRqpthBHKl647dlyEKrySlNRSrtz"
    volumes:
      - quiz_competition_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "aon9den3vA-K77x5fqPCay4QrUlph_ei"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  quiz_competition_data:
